heat_template_version: 2014-10-16

description: >
  This template will provision the minimum number of required nodes, as well
  it will setup all of the required lbaas vips.

parameters:
  release_tag:
    type: string
    default: "12.0.7"
  keystone_admin_api_port:
    description: The port keystone-admin-api is listening on.
    type: number
    default: 35357
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  keystone_api_port:
    description: The port keystone-api is listening on.
    type: number
    default: 5000
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  nova_api_metadata_port:
    description: The port nova-api-metadata is listening on.
    type: number
    default: 8775
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  nova_api_port:
    description: The port nova-api is listening on.
    type: number
    default: 8774
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  nova_api_ec2_port:
    description: The port nova-api is listening on.
    type: number
    default: 8773
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  glance_api_port:
    description: The port nova-api is listening on.
    type: number
    default: 9292
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  glance_registry_port:
    description: The port nova-api is listening on.
    type: number
    default: 9191
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  cinder_api_port:
    description: The port cinder-api is listening on.
    type: number
    default: 8776
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  ceilometer_api_port:
    description: The port ceilometer-api is listening on.
    type: number
    default: 8777
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  heat_api_port:
    description: The port heat-api is listening on.
    type: number
    default: 8004
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  heat_cfn_api_port:
    description: The port heat-cfn-api is listening on.
    type: number
    default: 8000
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  heat_cloudwatch_api_port:
    description: The port heat-cloudwatch-api is listening on.
    type: number
    default: 8003
    constraints:
    - range:
        min: 1025
        max: 65535
      description: Must be an integer between 1025 and 65535.
  lb_algorithm:
    description: The algorithm used for the loadbalancer.
    type: string
    default: LEAST_CONNECTIONS
    constraints:
    - allowed_values:
      - LEAST_CONNECTIONS
      - ROUND_ROBIN
      description: |
        Must be a valid Rackspace Cloud Loadbalancer algorithm.

resources:
  deploy_ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      save_private_key: True
      name: deploy_key
  deployment_server:
    type: "OS::Nova::Server"
    properties:
      flavor: 1 GB General Purpose v1
      image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      key_name: shep
      user_data:
        str_replace:
          template: | 
            #!/bin/bash
            apt-get update
            apt-get install -y build-essential git python-dev

            # Setup SSH keys
            cat << 'EOH' |sudo tee /root/.ssh/id_rsa
            %ssh_priv_key%
            EOH
            chmod 600 /root/.ssh/id_rsa
            echo %ssh_pub_key% > /root/.ssh/id_rsa.pub
            cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys

            # Checkout openstack-ansible
            git clone -b %git_tag% https://github.com/openstack/openstack-ansible.git /opt/openstack-ansible
            pushd /opt/openstack-ansible
            scripts/bootstrap-ansible.sh
            popd
          params:
            "%ssh_priv_key%": { get_attr: [ deploy_ssh_key, private_key ] }
            "%ssh_pub_key%": { get_attr: [ deploy_ssh_key, public_key ] }
            "%git_tag%": { get_param: release_tag }
  nova-api-metadata:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: 2
      resource_def:
        type: "OS::Nova::Server"
        properties:
          flavor: 1 GB General Purpose v1
          image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
          key_name: shep
          user_data:
              str_replace:
                template: |
                  #!/bin/bash
                  apt-get update

                  # Setup SSH keys
                  echo %ssh_pub_key% >> /root/.ssh/authorized_keys
                params:
                  "%ssh_pub_key%": { get_attr: [ deploy_ssh_key, public_key ] }
  lb_nova_api_metadata:
    type: "Rackspace::Cloud::LoadBalancer"
    properties:
      name: "lb-nova-api-metadata"
      nodes:
      - addresses: { get_attr: [ nova-api-metadata, addresses, private, 0, addr ] }
        port: { get_param: nova_api_metadata_port }
        condition: ENABLED
      port: { get_param: nova_api_metadata_port }
      protocol: HTTP
      algorithm: { get_param: lb_algorithm }
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      healthMonitor:
        attemptsBeforeDeactivation: 3
        delay: 10
        timeout: 120
        type: HTTP
        path: "/"
        statusRegex: "."
        bodyRegex: "."
        
outputs:
  lb-nova-api-metadata:
    value: { get_attr: [lb_nova_api_metadata, PublicIp] }
  deploy_ssh_priv_key:
    value: { get_attr: [ deploy_ssh_key, private_key ] }
  metadata-ips:
    value: { get_attr: [ nova-api-metadata, addresses, private, 0, addr ] }
