heat_template_version: 2013-05-23

description: >
  This template will provision the minimum number of required nodes, as well
  it will setup all of the required lbaas vips.

parameters:
  resource_count:
    type: number
    default: 60
    constraints:
      - range: { min: 10, max: 600 }
        description: "Must be an integer between 10 and 600"

resources:
  private_net:
    type: "OS::Neutron::Net"

  private_subnet:
    type: "OS::Neutron::Subnet"
    properties:
      network_id: { get_resource: private_net }
      cidr: "10.100.100.0/22"

  test_servers:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: resource_count }
      resource_def:
        type: "OS::Nova::Server"
        properties:
          flavor: m1.small
          image: ubuntu-server-14.04
          key_name: shep
          networks: 
            - network: { get_resource: private_net }
          user_data: |
            #!/bin/bash
            apt-get install -y wget

  final_server:
    type: "OS::Nova::Server"
    depends_on: [ test_servers ]
    properties:
      flavor: m1.small
      image: ubuntu-server-14.04
      key_name: shep
      networks: 
        - network: { get_resource: private_net }
      user_data: |
        #!/bin/bash
        apt-get install -y wget
